### PR TITLE
adding CORS support for API

### PR DESCRIPTION
**Pull request by kastentx**
Adding CORS support. Merging with `max-base` rather than individual models.

### CODE REVIEW

**Review by bdwyer2 — APPROVED** [review]

**Comment by kastentx** [comment]
@bdwyer2 @ptitzler I've updated the pushed changes in this PR to match those from https://github.com/IBM/MAX-Image-Segmenter/pull/14

**Comment by kastentx** [comment]
one note... the following could be added to the indvidual Model READMEs to reflect this change:
<hr>
By default, Cross-Origin Resource Sharing (CORS) is disabled. To _enable_ CORS support, include the following -e flag with your run command:

```
$ docker run -it -e CORS_ENABLE='true' -p 5000:5000 <codait/model_image_name_here>
```

**Review by bdwyer2 — APPROVED** [review]
Currently `app.py` in the base image isn't used anywhere and eventually we will probably remove it but there is no harm in the changes you made.

**Comment by bdwyer2** [comment]
@kastentx can you please create a PR against the new `max-base` repo? https://github.com/ibm/max-base

The only change you really need is the 1 line addition to `requirements.txt`

**Pull request closed without merging**
